# The current version of Seanime (Do not change)
version = ''

[cache]
dir = '$SEANIME_DATA_DIR/cache'
transcodedir = '$SEANIME_DATA_DIR/cache/transcode'

[database]
name = 'seanime'

[extensions]
dir = '$SEANIME_DATA_DIR/extensions'

[logs]
dir = '$SEANIME_DATA_DIR/logs'

[manga]
downloaddir = '$SEANIME_DATA_DIR/manga'

[offline]
assetdir = '$SEANIME_DATA_DIR/offline/assets'
dir = '$SEANIME_DATA_DIR/offline'

[server]
host = '0.0.0.0'
offline = false
port = 8080
usebinarypath = true
password = 'your_password_here'

[web]
assetdir = '$SEANIME_DATA_DIR/assets'
